# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 567b1f7ea0de34e79c1690bb85dd31f9e5c812f5f1608d9525f9df552f9e4637d4c3ed0c681a637b0362c0540b44dc8b36a02e3a1f104c921bc9a6faed159507

test:
  secret_key_base: aef602b4c4cc4cbc8fa7d8cafe115d95e23939cf9cc6f854939fe9b66b24b076d87c329dbf8de3b6939f32e1926f8a9a7f88ac562c72435f9b01730a948b4301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
